// Mocks generated by Mockito 5.4.6 from annotations
// in nuevo_app/test/domain/usecases/user/get_preferences_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:nuevo_app/core/errors/failures.dart' as _i5;
import 'package:nuevo_app/domain/entities/preferences.dart' as _i7;
import 'package:nuevo_app/domain/entities/user.dart' as _i6;
import 'package:nuevo_app/domain/repositories/user_repository.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i3.UserRepository {
  MockUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.User>> getUserProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getUserProfile, []),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.User>>.value(
              _FakeEither_0<_i5.Failure, _i6.User>(
                this,
                Invocation.method(#getUserProfile, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.User>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.User>> updateProfile({
    String? name,
    String? phoneNumber,
    String? profileImageUrl,
    String? dateOfBirth,
    double? height,
    double? weight,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [], {
              #name: name,
              #phoneNumber: phoneNumber,
              #profileImageUrl: profileImageUrl,
              #dateOfBirth: dateOfBirth,
              #height: height,
              #weight: weight,
            }),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.User>>.value(
              _FakeEither_0<_i5.Failure, _i6.User>(
                this,
                Invocation.method(#updateProfile, [], {
                  #name: name,
                  #phoneNumber: phoneNumber,
                  #profileImageUrl: profileImageUrl,
                  #dateOfBirth: dateOfBirth,
                  #height: height,
                  #weight: weight,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.User>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.Preferences>> updatePreferences(
    _i7.Preferences? preferences,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updatePreferences, [preferences]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i7.Preferences>>.value(
                  _FakeEither_0<_i5.Failure, _i7.Preferences>(
                    this,
                    Invocation.method(#updatePreferences, [preferences]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i7.Preferences>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.Preferences>> getPreferences() =>
      (super.noSuchMethod(
            Invocation.method(#getPreferences, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i7.Preferences>>.value(
                  _FakeEither_0<_i5.Failure, _i7.Preferences>(
                    this,
                    Invocation.method(#getPreferences, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i7.Preferences>>);
}
