// Mocks generated by Mockito 5.4.6 from annotations
// in nuevo_app/test/data/repositories/auth_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:nuevo_app/data/datasources/local/local_data_source.dart'
    as _i23;
import 'package:nuevo_app/data/datasources/remote/api_client.dart' as _i4;
import 'package:nuevo_app/data/models/active_progress_model.dart' as _i19;
import 'package:nuevo_app/data/models/api_response.dart' as _i2;
import 'package:nuevo_app/data/models/appointment_model.dart' as _i12;
import 'package:nuevo_app/data/models/auth_response_model.dart' as _i6;
import 'package:nuevo_app/data/models/billing_response_model.dart' as _i22;
import 'package:nuevo_app/data/models/daily_exercise_model.dart' as _i16;
import 'package:nuevo_app/data/models/diet_plan_model.dart' as _i15;
import 'package:nuevo_app/data/models/goal_model.dart' as _i13;
import 'package:nuevo_app/data/models/lab_report_model.dart' as _i10;
import 'package:nuevo_app/data/models/lab_request_model.dart' as _i9;
import 'package:nuevo_app/data/models/payment_integration_models.dart' as _i21;
import 'package:nuevo_app/data/models/phase_model.dart' as _i14;
import 'package:nuevo_app/data/models/preferences_model.dart' as _i8;
import 'package:nuevo_app/data/models/session_progress_model.dart' as _i18;
import 'package:nuevo_app/data/models/specialist_model.dart' as _i20;
import 'package:nuevo_app/data/models/subscription_model.dart' as _i3;
import 'package:nuevo_app/data/models/user_model.dart' as _i7;
import 'package:nuevo_app/data/models/weekly_schedule_model.dart' as _i17;
import 'package:nuevo_app/domain/models/health/patient_habit_history.dart'
    as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeApiResponse_0<T> extends _i1.SmartFake
    implements _i2.ApiResponse<T> {
  _FakeApiResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSubscriptionModel_1 extends _i1.SmartFake
    implements _i3.SubscriptionModel {
  _FakeSubscriptionModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i4.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.ApiResponse<void>> sendOtp(_i6.SendOtpRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#sendOtp, [request]),
            returnValue: _i5.Future<_i2.ApiResponse<void>>.value(
              _FakeApiResponse_0<void>(
                this,
                Invocation.method(#sendOtp, [request]),
              ),
            ),
          )
          as _i5.Future<_i2.ApiResponse<void>>);

  @override
  _i5.Future<_i2.ApiResponse<_i6.AuthResponseData>> verifyOtp(
    _i6.VerifyOtpRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyOtp, [request]),
            returnValue:
                _i5.Future<_i2.ApiResponse<_i6.AuthResponseData>>.value(
                  _FakeApiResponse_0<_i6.AuthResponseData>(
                    this,
                    Invocation.method(#verifyOtp, [request]),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResponse<_i6.AuthResponseData>>);

  @override
  _i5.Future<_i2.ApiResponse<_i6.AuthResponseData>> login(
    _i6.LoginRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#login, [request]),
            returnValue:
                _i5.Future<_i2.ApiResponse<_i6.AuthResponseData>>.value(
                  _FakeApiResponse_0<_i6.AuthResponseData>(
                    this,
                    Invocation.method(#login, [request]),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResponse<_i6.AuthResponseData>>);

  @override
  _i5.Future<_i2.ApiResponse<_i6.AuthResponseData>> register(
    _i6.RegisterRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#register, [request]),
            returnValue:
                _i5.Future<_i2.ApiResponse<_i6.AuthResponseData>>.value(
                  _FakeApiResponse_0<_i6.AuthResponseData>(
                    this,
                    Invocation.method(#register, [request]),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResponse<_i6.AuthResponseData>>);

  @override
  _i5.Future<_i2.ApiResponse<_i6.AuthResponseData>> googleLogin(
    String? token,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#googleLogin, [token]),
            returnValue:
                _i5.Future<_i2.ApiResponse<_i6.AuthResponseData>>.value(
                  _FakeApiResponse_0<_i6.AuthResponseData>(
                    this,
                    Invocation.method(#googleLogin, [token]),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResponse<_i6.AuthResponseData>>);

  @override
  _i5.Future<_i2.ApiResponse<_i6.AuthResponseData>> appleLogin({
    required String? token,
    String? firstName,
    String? lastName,
    String? email,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#appleLogin, [], {
              #token: token,
              #firstName: firstName,
              #lastName: lastName,
              #email: email,
            }),
            returnValue:
                _i5.Future<_i2.ApiResponse<_i6.AuthResponseData>>.value(
                  _FakeApiResponse_0<_i6.AuthResponseData>(
                    this,
                    Invocation.method(#appleLogin, [], {
                      #token: token,
                      #firstName: firstName,
                      #lastName: lastName,
                      #email: email,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResponse<_i6.AuthResponseData>>);

  @override
  _i5.Future<_i2.ApiResponse<void>> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i5.Future<_i2.ApiResponse<void>>.value(
              _FakeApiResponse_0<void>(this, Invocation.method(#logout, [])),
            ),
          )
          as _i5.Future<_i2.ApiResponse<void>>);

  @override
  _i5.Future<_i2.ApiResponse<void>> forgotPassword(
    _i6.ForgotPasswordRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#forgotPassword, [request]),
            returnValue: _i5.Future<_i2.ApiResponse<void>>.value(
              _FakeApiResponse_0<void>(
                this,
                Invocation.method(#forgotPassword, [request]),
              ),
            ),
          )
          as _i5.Future<_i2.ApiResponse<void>>);

  @override
  _i5.Future<_i2.ApiResponse<void>> resendResetCode(
    _i6.ForgotPasswordRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resendResetCode, [request]),
            returnValue: _i5.Future<_i2.ApiResponse<void>>.value(
              _FakeApiResponse_0<void>(
                this,
                Invocation.method(#resendResetCode, [request]),
              ),
            ),
          )
          as _i5.Future<_i2.ApiResponse<void>>);

  @override
  _i5.Future<_i2.ApiResponse<void>> verifyResetCode(
    _i6.VerifyResetCodeRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyResetCode, [request]),
            returnValue: _i5.Future<_i2.ApiResponse<void>>.value(
              _FakeApiResponse_0<void>(
                this,
                Invocation.method(#verifyResetCode, [request]),
              ),
            ),
          )
          as _i5.Future<_i2.ApiResponse<void>>);

  @override
  _i5.Future<_i2.ApiResponse<void>> resetPassword(
    _i6.ResetPasswordRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [request]),
            returnValue: _i5.Future<_i2.ApiResponse<void>>.value(
              _FakeApiResponse_0<void>(
                this,
                Invocation.method(#resetPassword, [request]),
              ),
            ),
          )
          as _i5.Future<_i2.ApiResponse<void>>);

  @override
  _i5.Future<_i2.ApiResponse<_i7.UserModel>> getUserProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getUserProfile, []),
            returnValue: _i5.Future<_i2.ApiResponse<_i7.UserModel>>.value(
              _FakeApiResponse_0<_i7.UserModel>(
                this,
                Invocation.method(#getUserProfile, []),
              ),
            ),
          )
          as _i5.Future<_i2.ApiResponse<_i7.UserModel>>);

  @override
  _i5.Future<_i2.ApiResponse<_i7.UserModel>> updateProfile(dynamic data) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [data]),
            returnValue: _i5.Future<_i2.ApiResponse<_i7.UserModel>>.value(
              _FakeApiResponse_0<_i7.UserModel>(
                this,
                Invocation.method(#updateProfile, [data]),
              ),
            ),
          )
          as _i5.Future<_i2.ApiResponse<_i7.UserModel>>);

  @override
  _i5.Future<_i2.ApiResponse<void>> checkEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#checkEmail, [email]),
            returnValue: _i5.Future<_i2.ApiResponse<void>>.value(
              _FakeApiResponse_0<void>(
                this,
                Invocation.method(#checkEmail, [email]),
              ),
            ),
          )
          as _i5.Future<_i2.ApiResponse<void>>);

  @override
  _i5.Future<_i2.ApiResponse<_i8.PreferencesModel>> updatePreferences(
    _i8.PreferencesModel? preferences,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updatePreferences, [preferences]),
            returnValue:
                _i5.Future<_i2.ApiResponse<_i8.PreferencesModel>>.value(
                  _FakeApiResponse_0<_i8.PreferencesModel>(
                    this,
                    Invocation.method(#updatePreferences, [preferences]),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResponse<_i8.PreferencesModel>>);

  @override
  _i5.Future<_i2.ApiResponse<_i8.PreferencesModel>> getPreferences() =>
      (super.noSuchMethod(
            Invocation.method(#getPreferences, []),
            returnValue:
                _i5.Future<_i2.ApiResponse<_i8.PreferencesModel>>.value(
                  _FakeApiResponse_0<_i8.PreferencesModel>(
                    this,
                    Invocation.method(#getPreferences, []),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResponse<_i8.PreferencesModel>>);

  @override
  _i5.Future<_i3.SubscriptionModel> getSubscriptionStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getSubscriptionStatus, []),
            returnValue: _i5.Future<_i3.SubscriptionModel>.value(
              _FakeSubscriptionModel_1(
                this,
                Invocation.method(#getSubscriptionStatus, []),
              ),
            ),
          )
          as _i5.Future<_i3.SubscriptionModel>);

  @override
  _i5.Future<_i3.SubscriptionModel> getSubscriptionDetails() =>
      (super.noSuchMethod(
            Invocation.method(#getSubscriptionDetails, []),
            returnValue: _i5.Future<_i3.SubscriptionModel>.value(
              _FakeSubscriptionModel_1(
                this,
                Invocation.method(#getSubscriptionDetails, []),
              ),
            ),
          )
          as _i5.Future<_i3.SubscriptionModel>);

  @override
  _i5.Future<_i2.ApiResponse<_i9.LabRequestData>> createLabRequest(
    _i9.CreateLabRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createLabRequest, [request]),
            returnValue: _i5.Future<_i2.ApiResponse<_i9.LabRequestData>>.value(
              _FakeApiResponse_0<_i9.LabRequestData>(
                this,
                Invocation.method(#createLabRequest, [request]),
              ),
            ),
          )
          as _i5.Future<_i2.ApiResponse<_i9.LabRequestData>>);

  @override
  _i5.Future<_i2.ApiResponse<_i9.LabRequestListResponseData>>
  getLabRequests() =>
      (super.noSuchMethod(
            Invocation.method(#getLabRequests, []),
            returnValue:
                _i5.Future<
                  _i2.ApiResponse<_i9.LabRequestListResponseData>
                >.value(
                  _FakeApiResponse_0<_i9.LabRequestListResponseData>(
                    this,
                    Invocation.method(#getLabRequests, []),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResponse<_i9.LabRequestListResponseData>>);

  @override
  _i5.Future<_i2.ApiResponse<_i9.LabRequestData>> getLabRequestById(
    String? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getLabRequestById, [id]),
            returnValue: _i5.Future<_i2.ApiResponse<_i9.LabRequestData>>.value(
              _FakeApiResponse_0<_i9.LabRequestData>(
                this,
                Invocation.method(#getLabRequestById, [id]),
              ),
            ),
          )
          as _i5.Future<_i2.ApiResponse<_i9.LabRequestData>>);

  @override
  _i5.Future<_i2.ApiResponse<_i10.LabReportListData>> getLabReports() =>
      (super.noSuchMethod(
            Invocation.method(#getLabReports, []),
            returnValue:
                _i5.Future<_i2.ApiResponse<_i10.LabReportListData>>.value(
                  _FakeApiResponse_0<_i10.LabReportListData>(
                    this,
                    Invocation.method(#getLabReports, []),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResponse<_i10.LabReportListData>>);

  @override
  _i5.Future<_i2.ApiResponse<_i10.LabReportDetailData>> getLabReportDetails(
    String? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getLabReportDetails, [id]),
            returnValue:
                _i5.Future<_i2.ApiResponse<_i10.LabReportDetailData>>.value(
                  _FakeApiResponse_0<_i10.LabReportDetailData>(
                    this,
                    Invocation.method(#getLabReportDetails, [id]),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResponse<_i10.LabReportDetailData>>);

  @override
  _i5.Future<_i2.ApiResponse<List<_i11.PatientHabitHistory>>>
  getPatientHabitHistory(String? date) =>
      (super.noSuchMethod(
            Invocation.method(#getPatientHabitHistory, [date]),
            returnValue:
                _i5.Future<
                  _i2.ApiResponse<List<_i11.PatientHabitHistory>>
                >.value(
                  _FakeApiResponse_0<List<_i11.PatientHabitHistory>>(
                    this,
                    Invocation.method(#getPatientHabitHistory, [date]),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResponse<List<_i11.PatientHabitHistory>>>);

  @override
  _i5.Future<_i2.ApiResponse<List<_i11.PatientHabitHistory>>>
  getPatientHabitHistoryAll() =>
      (super.noSuchMethod(
            Invocation.method(#getPatientHabitHistoryAll, []),
            returnValue:
                _i5.Future<
                  _i2.ApiResponse<List<_i11.PatientHabitHistory>>
                >.value(
                  _FakeApiResponse_0<List<_i11.PatientHabitHistory>>(
                    this,
                    Invocation.method(#getPatientHabitHistoryAll, []),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResponse<List<_i11.PatientHabitHistory>>>);

  @override
  _i5.Future<_i2.ApiResponse<_i11.PatientHabitHistory>> savePatientHabitHistory(
    _i11.PatientHabitHistory? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#savePatientHabitHistory, [data]),
            returnValue:
                _i5.Future<_i2.ApiResponse<_i11.PatientHabitHistory>>.value(
                  _FakeApiResponse_0<_i11.PatientHabitHistory>(
                    this,
                    Invocation.method(#savePatientHabitHistory, [data]),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResponse<_i11.PatientHabitHistory>>);

  @override
  _i5.Future<_i2.ApiResponse<_i12.TimeSlotResponse>> getTimeSlots({
    required String? memberId,
    required String? date,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getTimeSlots, [], {
              #memberId: memberId,
              #date: date,
            }),
            returnValue:
                _i5.Future<_i2.ApiResponse<_i12.TimeSlotResponse>>.value(
                  _FakeApiResponse_0<_i12.TimeSlotResponse>(
                    this,
                    Invocation.method(#getTimeSlots, [], {
                      #memberId: memberId,
                      #date: date,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResponse<_i12.TimeSlotResponse>>);

  @override
  _i5.Future<_i2.ApiResponse<_i12.AppointmentResponseData>> bookAppointment({
    required String? memberId,
    required String? startTime,
    String? notes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#bookAppointment, [], {
              #memberId: memberId,
              #startTime: startTime,
              #notes: notes,
            }),
            returnValue:
                _i5.Future<_i2.ApiResponse<_i12.AppointmentResponseData>>.value(
                  _FakeApiResponse_0<_i12.AppointmentResponseData>(
                    this,
                    Invocation.method(#bookAppointment, [], {
                      #memberId: memberId,
                      #startTime: startTime,
                      #notes: notes,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResponse<_i12.AppointmentResponseData>>);

  @override
  _i5.Future<_i2.ApiResponse<_i12.AppointmentResponseData>> getAppointmentById(
    String? appointmentId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAppointmentById, [appointmentId]),
            returnValue:
                _i5.Future<_i2.ApiResponse<_i12.AppointmentResponseData>>.value(
                  _FakeApiResponse_0<_i12.AppointmentResponseData>(
                    this,
                    Invocation.method(#getAppointmentById, [appointmentId]),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResponse<_i12.AppointmentResponseData>>);

  @override
  _i5.Future<_i2.ApiResponse<_i12.AppointmentResponseData>> updateAppointment(
    String? bookingId,
    _i12.UpdateAppointmentRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateAppointment, [bookingId, request]),
            returnValue:
                _i5.Future<_i2.ApiResponse<_i12.AppointmentResponseData>>.value(
                  _FakeApiResponse_0<_i12.AppointmentResponseData>(
                    this,
                    Invocation.method(#updateAppointment, [bookingId, request]),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResponse<_i12.AppointmentResponseData>>);

  @override
  _i5.Future<_i2.ApiResponse<_i12.CancelAppointmentResponseData>>
  cancelAppointment(String? bookingId) =>
      (super.noSuchMethod(
            Invocation.method(#cancelAppointment, [bookingId]),
            returnValue:
                _i5.Future<
                  _i2.ApiResponse<_i12.CancelAppointmentResponseData>
                >.value(
                  _FakeApiResponse_0<_i12.CancelAppointmentResponseData>(
                    this,
                    Invocation.method(#cancelAppointment, [bookingId]),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResponse<_i12.CancelAppointmentResponseData>>);

  @override
  _i5.Future<_i2.ApiResponse<_i12.UserAppointmentsResponse>>
  getUserAppointments() =>
      (super.noSuchMethod(
            Invocation.method(#getUserAppointments, []),
            returnValue:
                _i5.Future<
                  _i2.ApiResponse<_i12.UserAppointmentsResponse>
                >.value(
                  _FakeApiResponse_0<_i12.UserAppointmentsResponse>(
                    this,
                    Invocation.method(#getUserAppointments, []),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResponse<_i12.UserAppointmentsResponse>>);

  @override
  _i5.Future<_i2.ApiResponse<List<_i13.GoalModel>>> getGoals() =>
      (super.noSuchMethod(
            Invocation.method(#getGoals, []),
            returnValue:
                _i5.Future<_i2.ApiResponse<List<_i13.GoalModel>>>.value(
                  _FakeApiResponse_0<List<_i13.GoalModel>>(
                    this,
                    Invocation.method(#getGoals, []),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResponse<List<_i13.GoalModel>>>);

  @override
  _i5.Future<_i2.ApiResponse<_i13.GoalModel>> createGoal(
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createGoal, [data]),
            returnValue: _i5.Future<_i2.ApiResponse<_i13.GoalModel>>.value(
              _FakeApiResponse_0<_i13.GoalModel>(
                this,
                Invocation.method(#createGoal, [data]),
              ),
            ),
          )
          as _i5.Future<_i2.ApiResponse<_i13.GoalModel>>);

  @override
  _i5.Future<_i2.ApiResponse<_i13.GoalModel>> getGoalById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getGoalById, [id]),
            returnValue: _i5.Future<_i2.ApiResponse<_i13.GoalModel>>.value(
              _FakeApiResponse_0<_i13.GoalModel>(
                this,
                Invocation.method(#getGoalById, [id]),
              ),
            ),
          )
          as _i5.Future<_i2.ApiResponse<_i13.GoalModel>>);

  @override
  _i5.Future<_i2.ApiResponse<_i13.GoalModel>> updateGoal(
    String? id,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateGoal, [id, data]),
            returnValue: _i5.Future<_i2.ApiResponse<_i13.GoalModel>>.value(
              _FakeApiResponse_0<_i13.GoalModel>(
                this,
                Invocation.method(#updateGoal, [id, data]),
              ),
            ),
          )
          as _i5.Future<_i2.ApiResponse<_i13.GoalModel>>);

  @override
  _i5.Future<_i2.ApiResponse<void>> deleteGoal(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteGoal, [id]),
            returnValue: _i5.Future<_i2.ApiResponse<void>>.value(
              _FakeApiResponse_0<void>(
                this,
                Invocation.method(#deleteGoal, [id]),
              ),
            ),
          )
          as _i5.Future<_i2.ApiResponse<void>>);

  @override
  _i5.Future<_i2.ApiResponse<List<_i14.PhaseModel>>> getPhases() =>
      (super.noSuchMethod(
            Invocation.method(#getPhases, []),
            returnValue:
                _i5.Future<_i2.ApiResponse<List<_i14.PhaseModel>>>.value(
                  _FakeApiResponse_0<List<_i14.PhaseModel>>(
                    this,
                    Invocation.method(#getPhases, []),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResponse<List<_i14.PhaseModel>>>);

  @override
  _i5.Future<_i2.ApiResponse<_i14.PhaseModel>> getPhaseById(String? phaseId) =>
      (super.noSuchMethod(
            Invocation.method(#getPhaseById, [phaseId]),
            returnValue: _i5.Future<_i2.ApiResponse<_i14.PhaseModel>>.value(
              _FakeApiResponse_0<_i14.PhaseModel>(
                this,
                Invocation.method(#getPhaseById, [phaseId]),
              ),
            ),
          )
          as _i5.Future<_i2.ApiResponse<_i14.PhaseModel>>);

  @override
  _i5.Future<_i2.ApiResponse<_i14.ActivePhaseResponseModel>>
  getMyActivePhase() =>
      (super.noSuchMethod(
            Invocation.method(#getMyActivePhase, []),
            returnValue:
                _i5.Future<
                  _i2.ApiResponse<_i14.ActivePhaseResponseModel>
                >.value(
                  _FakeApiResponse_0<_i14.ActivePhaseResponseModel>(
                    this,
                    Invocation.method(#getMyActivePhase, []),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResponse<_i14.ActivePhaseResponseModel>>);

  @override
  _i5.Future<_i2.ApiResponse<_i14.WeeklyViewModel>> getCurrentWeeklyView() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentWeeklyView, []),
            returnValue:
                _i5.Future<_i2.ApiResponse<_i14.WeeklyViewModel>>.value(
                  _FakeApiResponse_0<_i14.WeeklyViewModel>(
                    this,
                    Invocation.method(#getCurrentWeeklyView, []),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResponse<_i14.WeeklyViewModel>>);

  @override
  _i5.Future<_i2.ApiResponse<_i14.PhaseProgressModel>> getPhaseProgress() =>
      (super.noSuchMethod(
            Invocation.method(#getPhaseProgress, []),
            returnValue:
                _i5.Future<_i2.ApiResponse<_i14.PhaseProgressModel>>.value(
                  _FakeApiResponse_0<_i14.PhaseProgressModel>(
                    this,
                    Invocation.method(#getPhaseProgress, []),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResponse<_i14.PhaseProgressModel>>);

  @override
  _i5.Future<_i2.ApiResponse<_i14.WeeklyViewModel>> getWeekByNumber(
    int? weekNumber,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getWeekByNumber, [weekNumber]),
            returnValue:
                _i5.Future<_i2.ApiResponse<_i14.WeeklyViewModel>>.value(
                  _FakeApiResponse_0<_i14.WeeklyViewModel>(
                    this,
                    Invocation.method(#getWeekByNumber, [weekNumber]),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResponse<_i14.WeeklyViewModel>>);

  @override
  _i5.Future<_i2.ApiResponse<_i14.PatientTaskModel>> getTaskById(
    String? taskId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTaskById, [taskId]),
            returnValue:
                _i5.Future<_i2.ApiResponse<_i14.PatientTaskModel>>.value(
                  _FakeApiResponse_0<_i14.PatientTaskModel>(
                    this,
                    Invocation.method(#getTaskById, [taskId]),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResponse<_i14.PatientTaskModel>>);

  @override
  _i5.Future<_i2.ApiResponse<_i14.PatientTaskModel>> markTaskCompleted(
    String? taskId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#markTaskCompleted, [taskId]),
            returnValue:
                _i5.Future<_i2.ApiResponse<_i14.PatientTaskModel>>.value(
                  _FakeApiResponse_0<_i14.PatientTaskModel>(
                    this,
                    Invocation.method(#markTaskCompleted, [taskId]),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResponse<_i14.PatientTaskModel>>);

  @override
  _i5.Future<_i2.ApiResponse<_i14.PatientTaskModel>> updateTaskStatus(
    String? taskId,
    String? statusValue,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateTaskStatus, [taskId, statusValue]),
            returnValue:
                _i5.Future<_i2.ApiResponse<_i14.PatientTaskModel>>.value(
                  _FakeApiResponse_0<_i14.PatientTaskModel>(
                    this,
                    Invocation.method(#updateTaskStatus, [taskId, statusValue]),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResponse<_i14.PatientTaskModel>>);

  @override
  _i5.Future<_i2.ApiResponse<_i15.DietPlanModel>> getDietPlan() =>
      (super.noSuchMethod(
            Invocation.method(#getDietPlan, []),
            returnValue: _i5.Future<_i2.ApiResponse<_i15.DietPlanModel>>.value(
              _FakeApiResponse_0<_i15.DietPlanModel>(
                this,
                Invocation.method(#getDietPlan, []),
              ),
            ),
          )
          as _i5.Future<_i2.ApiResponse<_i15.DietPlanModel>>);

  @override
  _i5.Future<_i2.ApiResponse<_i16.DailyExerciseModel>> getTodayExercise() =>
      (super.noSuchMethod(
            Invocation.method(#getTodayExercise, []),
            returnValue:
                _i5.Future<_i2.ApiResponse<_i16.DailyExerciseModel>>.value(
                  _FakeApiResponse_0<_i16.DailyExerciseModel>(
                    this,
                    Invocation.method(#getTodayExercise, []),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResponse<_i16.DailyExerciseModel>>);

  @override
  _i5.Future<_i2.ApiResponse<_i17.WeeklyScheduleModel>> getWeeklySchedule() =>
      (super.noSuchMethod(
            Invocation.method(#getWeeklySchedule, []),
            returnValue:
                _i5.Future<_i2.ApiResponse<_i17.WeeklyScheduleModel>>.value(
                  _FakeApiResponse_0<_i17.WeeklyScheduleModel>(
                    this,
                    Invocation.method(#getWeeklySchedule, []),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResponse<_i17.WeeklyScheduleModel>>);

  @override
  _i5.Future<_i2.ApiResponse<_i16.GuidedSessionModel>> getSessionDetails(
    String? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSessionDetails, [id]),
            returnValue:
                _i5.Future<_i2.ApiResponse<_i16.GuidedSessionModel>>.value(
                  _FakeApiResponse_0<_i16.GuidedSessionModel>(
                    this,
                    Invocation.method(#getSessionDetails, [id]),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResponse<_i16.GuidedSessionModel>>);

  @override
  _i5.Future<_i2.ApiResponse<_i18.SessionProgressModel>> startSession(
    String? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#startSession, [id]),
            returnValue:
                _i5.Future<_i2.ApiResponse<_i18.SessionProgressModel>>.value(
                  _FakeApiResponse_0<_i18.SessionProgressModel>(
                    this,
                    Invocation.method(#startSession, [id]),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResponse<_i18.SessionProgressModel>>);

  @override
  _i5.Future<_i2.ApiResponse<_i18.SessionProgressModel>> completeSession(
    String? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#completeSession, [id]),
            returnValue:
                _i5.Future<_i2.ApiResponse<_i18.SessionProgressModel>>.value(
                  _FakeApiResponse_0<_i18.SessionProgressModel>(
                    this,
                    Invocation.method(#completeSession, [id]),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResponse<_i18.SessionProgressModel>>);

  @override
  _i5.Future<_i2.ApiResponse<_i18.SessionProgressModel?>> syncSessionProgress(
    String? id,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#syncSessionProgress, [id, data]),
            returnValue:
                _i5.Future<_i2.ApiResponse<_i18.SessionProgressModel?>>.value(
                  _FakeApiResponse_0<_i18.SessionProgressModel?>(
                    this,
                    Invocation.method(#syncSessionProgress, [id, data]),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResponse<_i18.SessionProgressModel?>>);

  @override
  _i5.Future<_i2.ApiResponse<_i19.ActiveProgressModel?>> getActiveProgress() =>
      (super.noSuchMethod(
            Invocation.method(#getActiveProgress, []),
            returnValue:
                _i5.Future<_i2.ApiResponse<_i19.ActiveProgressModel?>>.value(
                  _FakeApiResponse_0<_i19.ActiveProgressModel?>(
                    this,
                    Invocation.method(#getActiveProgress, []),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResponse<_i19.ActiveProgressModel?>>);

  @override
  _i5.Future<_i2.ApiResponse<List<_i20.SpecialistModel>>> getMySpecialists() =>
      (super.noSuchMethod(
            Invocation.method(#getMySpecialists, []),
            returnValue:
                _i5.Future<_i2.ApiResponse<List<_i20.SpecialistModel>>>.value(
                  _FakeApiResponse_0<List<_i20.SpecialistModel>>(
                    this,
                    Invocation.method(#getMySpecialists, []),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResponse<List<_i20.SpecialistModel>>>);

  @override
  _i5.Future<_i2.ApiResponse<_i20.SpecialistModel>> getSpecialistDetails(
    String? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSpecialistDetails, [id]),
            returnValue:
                _i5.Future<_i2.ApiResponse<_i20.SpecialistModel>>.value(
                  _FakeApiResponse_0<_i20.SpecialistModel>(
                    this,
                    Invocation.method(#getSpecialistDetails, [id]),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResponse<_i20.SpecialistModel>>);

  @override
  _i5.Future<_i2.ApiResponse<_i21.SubscriptionPaywayDetails>>
  getSubscriptionPaywayDetails() =>
      (super.noSuchMethod(
            Invocation.method(#getSubscriptionPaywayDetails, []),
            returnValue:
                _i5.Future<
                  _i2.ApiResponse<_i21.SubscriptionPaywayDetails>
                >.value(
                  _FakeApiResponse_0<_i21.SubscriptionPaywayDetails>(
                    this,
                    Invocation.method(#getSubscriptionPaywayDetails, []),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResponse<_i21.SubscriptionPaywayDetails>>);

  @override
  _i5.Future<_i2.ApiResponse<_i21.PaymentCustomerDetails>> getSavedCards() =>
      (super.noSuchMethod(
            Invocation.method(#getSavedCards, []),
            returnValue:
                _i5.Future<_i2.ApiResponse<_i21.PaymentCustomerDetails>>.value(
                  _FakeApiResponse_0<_i21.PaymentCustomerDetails>(
                    this,
                    Invocation.method(#getSavedCards, []),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResponse<_i21.PaymentCustomerDetails>>);

  @override
  _i5.Future<_i2.ApiResponse<_i21.SingleUseTokenResponse>> tokenizeCard(
    Map<String, dynamic>? cardDetails,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#tokenizeCard, [cardDetails]),
            returnValue:
                _i5.Future<_i2.ApiResponse<_i21.SingleUseTokenResponse>>.value(
                  _FakeApiResponse_0<_i21.SingleUseTokenResponse>(
                    this,
                    Invocation.method(#tokenizeCard, [cardDetails]),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResponse<_i21.SingleUseTokenResponse>>);

  @override
  _i5.Future<_i2.ApiResponse<_i21.SaveCardResponse>> saveCard(
    String? singleUseTokenId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveCard, [singleUseTokenId]),
            returnValue:
                _i5.Future<_i2.ApiResponse<_i21.SaveCardResponse>>.value(
                  _FakeApiResponse_0<_i21.SaveCardResponse>(
                    this,
                    Invocation.method(#saveCard, [singleUseTokenId]),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResponse<_i21.SaveCardResponse>>);

  @override
  _i5.Future<_i2.ApiResponse<_i22.BillingResponseData>> getBillingDetails() =>
      (super.noSuchMethod(
            Invocation.method(#getBillingDetails, []),
            returnValue:
                _i5.Future<_i2.ApiResponse<_i22.BillingResponseData>>.value(
                  _FakeApiResponse_0<_i22.BillingResponseData>(
                    this,
                    Invocation.method(#getBillingDetails, []),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResponse<_i22.BillingResponseData>>);

  @override
  _i5.Future<_i2.ApiResponse<dynamic>> getQuestionnaire(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getQuestionnaire, [id]),
            returnValue: _i5.Future<_i2.ApiResponse<dynamic>>.value(
              _FakeApiResponse_0<dynamic>(
                this,
                Invocation.method(#getQuestionnaire, [id]),
              ),
            ),
          )
          as _i5.Future<_i2.ApiResponse<dynamic>>);

  @override
  _i5.Future<_i2.ApiResponse<dynamic>> submitQuestionnaire(
    String? patientTaskId,
    List<Map<String, dynamic>>? responses,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#submitQuestionnaire, [patientTaskId, responses]),
            returnValue: _i5.Future<_i2.ApiResponse<dynamic>>.value(
              _FakeApiResponse_0<dynamic>(
                this,
                Invocation.method(#submitQuestionnaire, [
                  patientTaskId,
                  responses,
                ]),
              ),
            ),
          )
          as _i5.Future<_i2.ApiResponse<dynamic>>);
}

/// A class which mocks [LocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalDataSource extends _i1.Mock implements _i23.LocalDataSource {
  MockLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> saveAccessToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveAccessToken, [token]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String?> getAccessToken() =>
      (super.noSuchMethod(
            Invocation.method(#getAccessToken, []),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<void> saveRefreshToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveRefreshToken, [token]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String?> getRefreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#getRefreshToken, []),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<void> saveUserId(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#saveUserId, [userId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String?> getUserId() =>
      (super.noSuchMethod(
            Invocation.method(#getUserId, []),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<void> clearSecureData() =>
      (super.noSuchMethod(
            Invocation.method(#clearSecureData, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  bool isFirstLaunch() =>
      (super.noSuchMethod(
            Invocation.method(#isFirstLaunch, []),
            returnValue: false,
          )
          as bool);

  @override
  _i5.Future<void> setFirstLaunchComplete() =>
      (super.noSuchMethod(
            Invocation.method(#setFirstLaunchComplete, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> setThemeMode(String? mode) =>
      (super.noSuchMethod(
            Invocation.method(#setThemeMode, [mode]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> setLanguage(String? language) =>
      (super.noSuchMethod(
            Invocation.method(#setLanguage, [language]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> setLastSyncTime(DateTime? time) =>
      (super.noSuchMethod(
            Invocation.method(#setLastSyncTime, [time]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> clearPreferences() =>
      (super.noSuchMethod(
            Invocation.method(#clearPreferences, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> handleFirstLaunch() =>
      (super.noSuchMethod(
            Invocation.method(#handleFirstLaunch, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> isLoggedIn() =>
      (super.noSuchMethod(
            Invocation.method(#isLoggedIn, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);
}
